name: Deploy to ECR and Upload to S3

on:
  push:
    branches:
      - branch_test

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_URI: 746611055047.dkr.ecr.ap-northeast-1.amazonaws.com/h4b-ecs-helloworld:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push Docker image to ECR
        run: |
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI
          docker pull $IMAGE_URI

      - name: Create container and extract files
        run: |
          docker create --name temp-container $IMAGE_URI
          mkdir -p ./extracted
          docker cp temp-container:/test.txt ./extracted/
          docker rm temp-container

      - name: Upload extracted files to S3
        run: |
          aws s3 cp ./extracted s3://jpix-test-lecture/ --recursive
